FROM node:13.12.0-alpine

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

COPY package.*json ./

RUN npm install --silent

RUN npm install -g react-scripts@4.0.3 --silent

COPY . ./

EXPOSE 3000

CMD ["npm","start"]
