version: '3'

services: 
    ps-ui-dev:
        container_name: ps-ui-dev
        build:
            context: .
            dockerfile: DockerFile
        ports: 
            - "1111:3000"
    ps-ui-prod:
        container_name: ps-ui-prod
        build:
            context: .
            dockerfile: DockerFile.prod
        ports: 
            - "5555:80"